// Generated by gencpp from file rl/SolveIk.msg
// DO NOT EDIT!


#ifndef RL_MESSAGE_SOLVEIK_H
#define RL_MESSAGE_SOLVEIK_H

#include <ros/service_traits.h>


#include <rl/SolveIkRequest.h>
#include <rl/SolveIkResponse.h>


namespace rl
{

struct SolveIk
{

typedef SolveIkRequest Request;
typedef SolveIkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolveIk
} // namespace rl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rl::SolveIk > {
  static const char* value()
  {
    return "6580254afbe9e0087fa243dc6fb4dd77";
  }

  static const char* value(const ::rl::SolveIk&) { return value(); }
};

template<>
struct DataType< ::rl::SolveIk > {
  static const char* value()
  {
    return "rl/SolveIk";
  }

  static const char* value(const ::rl::SolveIk&) { return value(); }
};


// service_traits::MD5Sum< ::rl::SolveIkRequest> should match
// service_traits::MD5Sum< ::rl::SolveIk >
template<>
struct MD5Sum< ::rl::SolveIkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rl::SolveIk >::value();
  }
  static const char* value(const ::rl::SolveIkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl::SolveIkRequest> should match
// service_traits::DataType< ::rl::SolveIk >
template<>
struct DataType< ::rl::SolveIkRequest>
{
  static const char* value()
  {
    return DataType< ::rl::SolveIk >::value();
  }
  static const char* value(const ::rl::SolveIkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rl::SolveIkResponse> should match
// service_traits::MD5Sum< ::rl::SolveIk >
template<>
struct MD5Sum< ::rl::SolveIkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rl::SolveIk >::value();
  }
  static const char* value(const ::rl::SolveIkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl::SolveIkResponse> should match
// service_traits::DataType< ::rl::SolveIk >
template<>
struct DataType< ::rl::SolveIkResponse>
{
  static const char* value()
  {
    return DataType< ::rl::SolveIk >::value();
  }
  static const char* value(const ::rl::SolveIkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RL_MESSAGE_SOLVEIK_H
